api:
  dashboard: true
  # we need to be insecure because of port http
  insecure: false
  debug: true

entrypoints:
  http:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: https
          scheme: https    

  https:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: master@traefiklands.rocks
      storage: /etc/letsencrypt/acme.json
      tlsChallenge: {}
      httpChallenge:
        # used during the challenge
        entryPoint: http
log:
  # only for development - default INFO
  level: DEBUG

ping:
  # this is default
  entryPoint: traefik

providers:
  # here we define the backend docker
  docker: 
    endpoint: "unix:///var/run/docker.sock"
    exposedbydefault: false
    network: proxy
    
  file:
    directory: /etc/traefik
    watch: true
