version: '3'

# We don't leave anything to chance (radom names):
# - define container name
# - define network bridge adapter

# Container with a static webside
services:
  traefik:
    image: traefik
    container_name: 'traefik'
    volumes:
     # bind the defaults into the container
      - ./traefik.yml:/etc/traefik/traefik.yaml
      # while we allready enabled docker as backend,
      # the socket must be exported to the container
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      # with the defaults (traefik.yml) this ports are there
      - 80:80
      - 8080:8080
    networks:
      - traefik

# We route through the defined bridge (00_initial_setup)
networks:
  traefik:
    external: true
      

