################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: true

################################################################
# EntryPoints configuration
################################################################

entryPoints:
  http:
    address: :80

################################################################
# Traefik logs configuration
################################################################

log:
  level: DEBUG

################################################################
# API and dashboard configuration
api:
  insecure: true
  dashboard: true

################################################################
# Ping configuration
################################################################

ping:
  entryPoint: traefik

################################################################
# Docker configuration backend
################################################################

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    defaultRule: "Host(`{{ normalize .Name }}`)"
    exposedByDefault: false
